// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FUNewsManagementSystemRepository.Models;

public partial class Comment
{
    public int CommentId { get; set; }

    public string Content { get; set; }

    public int Likes { get; set; }

    public DateTime CreatedDate { get; set; }

    public string NewsArticleId { get; set; }

    public short CreatedByAccountId { get; set; }

    public virtual SystemAccount CreatedByAccount { get; set; }

    public virtual NewsArticle NewsArticle { get; set; }
}