// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FUNewsManagementSystemRepository.Models;

public partial class FUNewsManagementContext : DbContext
{
    public FUNewsManagementContext(DbContextOptions<FUNewsManagementContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Comment> Comments { get; set; }

    public virtual DbSet<NewsArticle> NewsArticles { get; set; }

    public virtual DbSet<SystemAccount> SystemAccounts { get; set; }

    public virtual DbSet<Tag> Tags { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.ToTable("Category");

            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.CategoryDesciption)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ParentCategoryId).HasColumnName("ParentCategoryID");

            entity.HasOne(d => d.ParentCategory).WithMany(p => p.InverseParentCategory)
                .HasForeignKey(d => d.ParentCategoryId)
                .HasConstraintName("FK_Category_Category");
        });

        modelBuilder.Entity<Comment>(entity =>
        {
            entity.ToTable("Comment");

            entity.HasIndex(e => e.CreatedByAccountId, "IX_Comment_CreatedByAccountId");

            entity.HasIndex(e => e.NewsArticleId, "IX_Comment_NewsArticleId");

            entity.Property(e => e.Content).IsRequired();
            entity.Property(e => e.NewsArticleId)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.CreatedByAccount).WithMany(p => p.Comments)
                .HasForeignKey(d => d.CreatedByAccountId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.NewsArticle).WithMany(p => p.Comments)
                .HasForeignKey(d => d.NewsArticleId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<NewsArticle>(entity =>
        {
            entity.ToTable("NewsArticle");

            entity.Property(e => e.NewsArticleId)
                .HasMaxLength(20)
                .HasColumnName("NewsArticleID");
            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.CreatedById).HasColumnName("CreatedByID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Headline)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.NewsContent).HasMaxLength(4000);
            entity.Property(e => e.NewsSource).HasMaxLength(400);
            entity.Property(e => e.NewsTitle).HasMaxLength(400);
            entity.Property(e => e.UpdatedById).HasColumnName("UpdatedByID");

            entity.HasOne(d => d.Category).WithMany(p => p.NewsArticles)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_NewsArticle_Category");

            entity.HasOne(d => d.CreatedBy).WithMany(p => p.NewsArticles)
                .HasForeignKey(d => d.CreatedById)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_NewsArticle_SystemAccount");

            entity.HasMany(d => d.Tags).WithMany(p => p.NewsArticles)
                .UsingEntity<Dictionary<string, object>>(
                    "NewsTag",
                    r => r.HasOne<Tag>().WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_NewsTag_Tag"),
                    l => l.HasOne<NewsArticle>().WithMany()
                        .HasForeignKey("NewsArticleId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_NewsTag_NewsArticle"),
                    j =>
                    {
                        j.HasKey("NewsArticleId", "TagId");
                        j.ToTable("NewsTag");
                        j.IndexerProperty<string>("NewsArticleId")
                            .HasMaxLength(20)
                            .HasColumnName("NewsArticleID");
                        j.IndexerProperty<int>("TagId").HasColumnName("TagID");
                    });
        });

        modelBuilder.Entity<SystemAccount>(entity =>
        {
            entity.HasKey(e => e.AccountId);

            entity.ToTable("SystemAccount");

            entity.Property(e => e.AccountId).HasColumnName("AccountID");
            entity.Property(e => e.AccountEmail).HasMaxLength(70);
            entity.Property(e => e.AccountName).HasMaxLength(100);
            entity.Property(e => e.AccountPassword).HasMaxLength(70);
            entity.Property(e => e.AccountStatus)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Active");
        });

        modelBuilder.Entity<Tag>(entity =>
        {
            entity.HasKey(e => e.TagId).HasName("PK_HashTag");

            entity.ToTable("Tag");

            entity.Property(e => e.TagId)
                .ValueGeneratedNever()
                .HasColumnName("TagID");
            entity.Property(e => e.Note).HasMaxLength(400);
            entity.Property(e => e.TagName).HasMaxLength(50);
            entity.Property(e => e.TagStatus)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Active");
        });

		//Seed data

		modelBuilder.Entity<Category>().HasData(
			new Category { CategoryId = 1, CategoryName = "Academic news", CategoryDesciption = "This category can include articles about research findings, faculty appointments and promotions, and other academic-related announcements.", ParentCategoryId = null, IsActive = true },
			new Category { CategoryId = 2, CategoryName = "Student Affairs", CategoryDesciption = "This category can include articles about student activities, events, and initiatives, such as student clubs, organizations and sports.", ParentCategoryId = null, IsActive = true },
			new Category { CategoryId = 3, CategoryName = "Campus Safety", CategoryDesciption = "This category can include articles about incidents and safety measures implemented on campus to ensure the safety of students and faculty.", ParentCategoryId = null, IsActive = true },
			new Category { CategoryId = 4, CategoryName = "Alumni News", CategoryDesciption = "This category can include articles about the achievements and accomplishments of former students and alumni, such as graduations, job promotions and career successes.", ParentCategoryId = null, IsActive = true },
			new Category { CategoryId = 5, CategoryName = "Capstone Project News", CategoryDesciption = "This category is typically a comprehensive and detailed report created as part of an academic or professional capstone project.", ParentCategoryId = null, IsActive = false },
			new Category { CategoryId = 7, CategoryName = "WOWIE", CategoryDesciption = "WOWIE", ParentCategoryId = null, IsActive = true },
			new Category { CategoryId = 8, CategoryName = "Billard", CategoryDesciption = "Topic related to Billard", ParentCategoryId = null, IsActive = false }
		);

		modelBuilder.Entity<SystemAccount>().HasData(
			new SystemAccount { AccountId = 7, AccountName = "KhaiPQ", AccountEmail = "KhaiPQ28@gmail.com", AccountRole = 1, AccountPassword = "$2a$12$mPCblJm1hvWDN/suHR8pJulEmqEKt9KI7kKA9B4xP7czAG4JSrPf.", AccountStatus = "Active" },
			new SystemAccount { AccountId = 1, AccountName = "Emma William", AccountEmail = "EmmaWilliam@FUNewsManagement.org", AccountRole = 2, AccountPassword = "$2a$12$mPCblJm1hvWDN/suHR8pJulEmqEKt9KI7kKA9B4xP7czAG4JSrPf.", AccountStatus = "Active" },
			new SystemAccount { AccountId = 2, AccountName = "Olivia James", AccountEmail = "OliviaJames@FUNewsManagement.org", AccountRole = 2, AccountPassword = "$2a$12$mPCblJm1hvWDN/suHR8pJulEmqEKt9KI7kKA9B4xP7czAG4JSrPf.", AccountStatus = "Active" },
			new SystemAccount { AccountId = 3, AccountName = "Isabella David", AccountEmail = "IsabellaDavid@FUNewsManagement.org", AccountRole = 1, AccountPassword = "$2a$12$mPCblJm1hvWDN/suHR8pJulEmqEKt9KI7kKA9B4xP7czAG4JSrPf.", AccountStatus = "Inactive" },
			new SystemAccount { AccountId = 4, AccountName = "Michael Charlotte", AccountEmail = "MichaelCharlotte@FUNewsManagement.org", AccountRole = 1, AccountPassword = "$2a$12$mPCblJm1hvWDN/suHR8pJulEmqEKt9KI7kKA9B4xP7czAG4JSrPf.", AccountStatus = "Inactive" },
			new SystemAccount { AccountId = 5, AccountName = "Steve Paris", AccountEmail = "SteveParis@FUNewsManagement.org", AccountRole = 1, AccountPassword = "$2a$12$mPCblJm1hvWDN/suHR8pJulEmqEKt9KI7kKA9B4xP7czAG4JSrPf.", AccountStatus = "Active" },
			new SystemAccount { AccountId = 6, AccountName = "KhaiPQ", AccountEmail = "KhaiPQ2003@gmail.com", AccountRole = 1, AccountPassword = "$2a$12$mPCblJm1hvWDN/suHR8pJulEmqEKt9KI7kKA9B4xP7czAG4JSrPf.", AccountStatus = "Active" }
		);


		modelBuilder.Entity<Tag>().HasData(
			new Tag { TagId = 0, TagName = "Sport", Note = "Sport", TagStatus = "Active" },
			new Tag { TagId = 1, TagName = "Education", Note = "Education Note", TagStatus = "Active" },
			new Tag { TagId = 2, TagName = "Technology", Note = "Technology Note", TagStatus = "Active" },
			new Tag { TagId = 3, TagName = "Research", Note = "Research Note", TagStatus = "Active" },
			new Tag { TagId = 4, TagName = "Innovation", Note = "Innovation Note", TagStatus = "Active" },
			new Tag { TagId = 5, TagName = "Campus Life", Note = "Campus Life Note", TagStatus = "Active" },
			new Tag { TagId = 6, TagName = "Faculty", Note = "Faculty Achievements", TagStatus = "Active" },
			new Tag { TagId = 7, TagName = "Alumni", Note = "Alumni News", TagStatus = "Active" },
			new Tag { TagId = 8, TagName = "Events", Note = "University Events", TagStatus = "Active" },
			new Tag { TagId = 9, TagName = "Resources", Note = "Campus Resources", TagStatus = "Active" }
		);


		modelBuilder.Entity<NewsArticle>().HasData(
			new NewsArticle { NewsArticleId = "1", NewsTitle = "University FU Celebrates Success of Alumni in Various Fields", Headline = "University FU Celebrates Success of Alumni in Various Fields", CreatedDate = new DateTime(2024, 5, 5), NewsSource = "N/A", CategoryId = 4, NewsStatus = true, CreatedById = 1, UpdatedById = 1, ModifiedDate = new DateTime(2024, 5, 5) },
			new NewsArticle { NewsArticleId = "2", NewsTitle = "Alumni Association Launches Mentorship Program for Recent Graduates", Headline = "Alumni Association Launches Mentorship Program for Recent Graduates", CreatedDate = new DateTime(2024, 5, 5), NewsSource = "Internet", CategoryId = 4, NewsStatus = true, CreatedById = 1, UpdatedById = 1, ModifiedDate = new DateTime(2024, 5, 5) },
			new NewsArticle { NewsArticleId = "3", NewsTitle = "Academic Department Announces Groundbreaking Initiatives and Program Enhancements", Headline = "Academic Department Announces Groundbreaking Initiatives and Program Enhancements", CreatedDate = new DateTime(2024, 5, 5), NewsSource = "N/A", CategoryId = 1, NewsStatus = true, CreatedById = 2, UpdatedById = 2, ModifiedDate = new DateTime(2024, 5, 5) },
			new NewsArticle { NewsArticleId = "4", NewsTitle = "Renowned Scholar Appointed as Head of AI Department at FU", Headline = "Renowned Scholar Appointed as Head of AI Department at FU", CreatedDate = new DateTime(2024, 5, 5), NewsSource = "N/A", CategoryId = 1, NewsStatus = true, CreatedById = 2, UpdatedById = 2, ModifiedDate = new DateTime(2024, 5, 5) },
			new NewsArticle { NewsArticleId = "5", NewsTitle = "New Research Findings Shed Light on STEM", Headline = "New Research Findings Shed Light on STEM", CreatedDate = new DateTime(2024, 5, 5), NewsSource = "N/A", CategoryId = 1, NewsStatus = true, CreatedById = 2, UpdatedById = 2, ModifiedDate = new DateTime(2024, 5, 5) },
			new NewsArticle { NewsArticleId = "50", NewsTitle = "OmegaNice", Headline = "OmegaNice", CreatedDate = new DateTime(2026, 1, 23), NewsSource = "OmegaNice", CategoryId = 2, NewsStatus = true, CreatedById = 3, UpdatedById = 3, ModifiedDate = new DateTime(2026, 1, 23) }
		);

		OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}