// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FUNewsManagementSystemRepository.Models;

public partial class Tag
{
    public int TagId { get; set; }

    public string TagName { get; set; }

    public string Note { get; set; }

    public string TagStatus { get; set; }

    public virtual ICollection<NewsArticle> NewsArticles { get; set; } = new List<NewsArticle>();
}