// <auto-generated />
using System;
using FUNewsManagementSystemRepository.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PRN232.FUNewsManagement.Repo.Migrations
{
    [DbContext(typeof(FUNewsManagementContext))]
    partial class FUNewsManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FUNewsManagementSystemRepository.Models.Category", b =>
                {
                    b.Property<short>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("CategoryId"));

                    b.Property<string>("CategoryDesciption")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<short?>("ParentCategoryId")
                        .HasColumnType("smallint")
                        .HasColumnName("ParentCategoryID");

                    b.HasKey("CategoryId");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = (short)1,
                            CategoryDesciption = "This category can include articles about research findings, faculty appointments and promotions, and other academic-related announcements.",
                            CategoryName = "Academic news",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = (short)2,
                            CategoryDesciption = "This category can include articles about student activities, events, and initiatives, such as student clubs, organizations and sports.",
                            CategoryName = "Student Affairs",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = (short)3,
                            CategoryDesciption = "This category can include articles about incidents and safety measures implemented on campus to ensure the safety of students and faculty.",
                            CategoryName = "Campus Safety",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = (short)4,
                            CategoryDesciption = "This category can include articles about the achievements and accomplishments of former students and alumni, such as graduations, job promotions and career successes.",
                            CategoryName = "Alumni News",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = (short)5,
                            CategoryDesciption = "This category is typically a comprehensive and detailed report created as part of an academic or professional capstone project.",
                            CategoryName = "Capstone Project News",
                            IsActive = false
                        },
                        new
                        {
                            CategoryId = (short)7,
                            CategoryDesciption = "WOWIE",
                            CategoryName = "WOWIE",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = (short)8,
                            CategoryDesciption = "Topic related to Billard",
                            CategoryName = "Billard",
                            IsActive = false
                        });
                });

            modelBuilder.Entity("FUNewsManagementSystemRepository.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("CreatedByAccountId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("NewsArticleId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CommentId");

                    b.HasIndex(new[] { "CreatedByAccountId" }, "IX_Comment_CreatedByAccountId");

                    b.HasIndex(new[] { "NewsArticleId" }, "IX_Comment_NewsArticleId");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("FUNewsManagementSystemRepository.Models.NewsArticle", b =>
                {
                    b.Property<string>("NewsArticleId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NewsArticleID");

                    b.Property<short?>("CategoryId")
                        .HasColumnType("smallint")
                        .HasColumnName("CategoryID");

                    b.Property<short?>("CreatedById")
                        .HasColumnType("smallint")
                        .HasColumnName("CreatedByID");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("NewsContent")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("NewsSource")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool?>("NewsStatus")
                        .HasColumnType("bit");

                    b.Property<string>("NewsTitle")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<short?>("UpdatedById")
                        .HasColumnType("smallint")
                        .HasColumnName("UpdatedByID");

                    b.HasKey("NewsArticleId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedById");

                    b.ToTable("NewsArticle", (string)null);

                    b.HasData(
                        new
                        {
                            NewsArticleId = "1",
                            CategoryId = (short)4,
                            CreatedById = (short)1,
                            CreatedDate = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Headline = "University FU Celebrates Success of Alumni in Various Fields",
                            ModifiedDate = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NewsSource = "N/A",
                            NewsStatus = true,
                            NewsTitle = "University FU Celebrates Success of Alumni in Various Fields",
                            UpdatedById = (short)1
                        },
                        new
                        {
                            NewsArticleId = "2",
                            CategoryId = (short)4,
                            CreatedById = (short)1,
                            CreatedDate = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Headline = "Alumni Association Launches Mentorship Program for Recent Graduates",
                            ModifiedDate = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NewsSource = "Internet",
                            NewsStatus = true,
                            NewsTitle = "Alumni Association Launches Mentorship Program for Recent Graduates",
                            UpdatedById = (short)1
                        },
                        new
                        {
                            NewsArticleId = "3",
                            CategoryId = (short)1,
                            CreatedById = (short)2,
                            CreatedDate = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Headline = "Academic Department Announces Groundbreaking Initiatives and Program Enhancements",
                            ModifiedDate = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NewsSource = "N/A",
                            NewsStatus = true,
                            NewsTitle = "Academic Department Announces Groundbreaking Initiatives and Program Enhancements",
                            UpdatedById = (short)2
                        },
                        new
                        {
                            NewsArticleId = "4",
                            CategoryId = (short)1,
                            CreatedById = (short)2,
                            CreatedDate = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Headline = "Renowned Scholar Appointed as Head of AI Department at FU",
                            ModifiedDate = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NewsSource = "N/A",
                            NewsStatus = true,
                            NewsTitle = "Renowned Scholar Appointed as Head of AI Department at FU",
                            UpdatedById = (short)2
                        },
                        new
                        {
                            NewsArticleId = "5",
                            CategoryId = (short)1,
                            CreatedById = (short)2,
                            CreatedDate = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Headline = "New Research Findings Shed Light on STEM",
                            ModifiedDate = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NewsSource = "N/A",
                            NewsStatus = true,
                            NewsTitle = "New Research Findings Shed Light on STEM",
                            UpdatedById = (short)2
                        },
                        new
                        {
                            NewsArticleId = "50",
                            CategoryId = (short)2,
                            CreatedById = (short)3,
                            CreatedDate = new DateTime(2026, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Headline = "OmegaNice",
                            ModifiedDate = new DateTime(2026, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NewsSource = "OmegaNice",
                            NewsStatus = true,
                            NewsTitle = "OmegaNice",
                            UpdatedById = (short)3
                        });
                });

            modelBuilder.Entity("FUNewsManagementSystemRepository.Models.SystemAccount", b =>
                {
                    b.Property<short>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("AccountID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("AccountId"));

                    b.Property<string>("AccountEmail")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("AccountName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AccountPassword")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int?>("AccountRole")
                        .HasColumnType("int");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("AccountId");

                    b.ToTable("SystemAccount", (string)null);

                    b.HasData(
                        new
                        {
                            AccountId = (short)7,
                            AccountEmail = "KhaiPQ28@gmail.com",
                            AccountName = "KhaiPQ",
                            AccountPassword = "$2a$12$mPCblJm1hvWDN/suHR8pJulEmqEKt9KI7kKA9B4xP7czAG4JSrPf.",
                            AccountRole = 1,
                            AccountStatus = "Active"
                        },
                        new
                        {
                            AccountId = (short)1,
                            AccountEmail = "EmmaWilliam@FUNewsManagement.org",
                            AccountName = "Emma William",
                            AccountPassword = "$2a$12$mPCblJm1hvWDN/suHR8pJulEmqEKt9KI7kKA9B4xP7czAG4JSrPf.",
                            AccountRole = 2,
                            AccountStatus = "Active"
                        },
                        new
                        {
                            AccountId = (short)2,
                            AccountEmail = "OliviaJames@FUNewsManagement.org",
                            AccountName = "Olivia James",
                            AccountPassword = "$2a$12$mPCblJm1hvWDN/suHR8pJulEmqEKt9KI7kKA9B4xP7czAG4JSrPf.",
                            AccountRole = 2,
                            AccountStatus = "Active"
                        },
                        new
                        {
                            AccountId = (short)3,
                            AccountEmail = "IsabellaDavid@FUNewsManagement.org",
                            AccountName = "Isabella David",
                            AccountPassword = "$2a$12$mPCblJm1hvWDN/suHR8pJulEmqEKt9KI7kKA9B4xP7czAG4JSrPf.",
                            AccountRole = 1,
                            AccountStatus = "Inactive"
                        },
                        new
                        {
                            AccountId = (short)4,
                            AccountEmail = "MichaelCharlotte@FUNewsManagement.org",
                            AccountName = "Michael Charlotte",
                            AccountPassword = "$2a$12$mPCblJm1hvWDN/suHR8pJulEmqEKt9KI7kKA9B4xP7czAG4JSrPf.",
                            AccountRole = 1,
                            AccountStatus = "Inactive"
                        },
                        new
                        {
                            AccountId = (short)5,
                            AccountEmail = "SteveParis@FUNewsManagement.org",
                            AccountName = "Steve Paris",
                            AccountPassword = "$2a$12$mPCblJm1hvWDN/suHR8pJulEmqEKt9KI7kKA9B4xP7czAG4JSrPf.",
                            AccountRole = 1,
                            AccountStatus = "Active"
                        },
                        new
                        {
                            AccountId = (short)6,
                            AccountEmail = "KhaiPQ2003@gmail.com",
                            AccountName = "KhaiPQ",
                            AccountPassword = "$2a$12$mPCblJm1hvWDN/suHR8pJulEmqEKt9KI7kKA9B4xP7czAG4JSrPf.",
                            AccountRole = 1,
                            AccountStatus = "Active"
                        });
                });

            modelBuilder.Entity("FUNewsManagementSystemRepository.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("TagID");

                    b.Property<string>("Note")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("TagName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TagStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("TagId")
                        .HasName("PK_HashTag");

                    b.ToTable("Tag", (string)null);

                    b.HasData(
                        new
                        {
                            TagId = 0,
                            Note = "Sport",
                            TagName = "Sport",
                            TagStatus = "Active"
                        },
                        new
                        {
                            TagId = 1,
                            Note = "Education Note",
                            TagName = "Education",
                            TagStatus = "Active"
                        },
                        new
                        {
                            TagId = 2,
                            Note = "Technology Note",
                            TagName = "Technology",
                            TagStatus = "Active"
                        },
                        new
                        {
                            TagId = 3,
                            Note = "Research Note",
                            TagName = "Research",
                            TagStatus = "Active"
                        },
                        new
                        {
                            TagId = 4,
                            Note = "Innovation Note",
                            TagName = "Innovation",
                            TagStatus = "Active"
                        },
                        new
                        {
                            TagId = 5,
                            Note = "Campus Life Note",
                            TagName = "Campus Life",
                            TagStatus = "Active"
                        },
                        new
                        {
                            TagId = 6,
                            Note = "Faculty Achievements",
                            TagName = "Faculty",
                            TagStatus = "Active"
                        },
                        new
                        {
                            TagId = 7,
                            Note = "Alumni News",
                            TagName = "Alumni",
                            TagStatus = "Active"
                        },
                        new
                        {
                            TagId = 8,
                            Note = "University Events",
                            TagName = "Events",
                            TagStatus = "Active"
                        },
                        new
                        {
                            TagId = 9,
                            Note = "Campus Resources",
                            TagName = "Resources",
                            TagStatus = "Active"
                        });
                });

            modelBuilder.Entity("NewsTag", b =>
                {
                    b.Property<string>("NewsArticleId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NewsArticleID");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("TagID");

                    b.HasKey("NewsArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("NewsTag", (string)null);
                });

            modelBuilder.Entity("FUNewsManagementSystemRepository.Models.Category", b =>
                {
                    b.HasOne("FUNewsManagementSystemRepository.Models.Category", "ParentCategory")
                        .WithMany("InverseParentCategory")
                        .HasForeignKey("ParentCategoryId")
                        .HasConstraintName("FK_Category_Category");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("FUNewsManagementSystemRepository.Models.Comment", b =>
                {
                    b.HasOne("FUNewsManagementSystemRepository.Models.SystemAccount", "CreatedByAccount")
                        .WithMany("Comments")
                        .HasForeignKey("CreatedByAccountId")
                        .IsRequired();

                    b.HasOne("FUNewsManagementSystemRepository.Models.NewsArticle", "NewsArticle")
                        .WithMany("Comments")
                        .HasForeignKey("NewsArticleId")
                        .IsRequired();

                    b.Navigation("CreatedByAccount");

                    b.Navigation("NewsArticle");
                });

            modelBuilder.Entity("FUNewsManagementSystemRepository.Models.NewsArticle", b =>
                {
                    b.HasOne("FUNewsManagementSystemRepository.Models.Category", "Category")
                        .WithMany("NewsArticles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_NewsArticle_Category");

                    b.HasOne("FUNewsManagementSystemRepository.Models.SystemAccount", "CreatedBy")
                        .WithMany("NewsArticles")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_NewsArticle_SystemAccount");

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("NewsTag", b =>
                {
                    b.HasOne("FUNewsManagementSystemRepository.Models.NewsArticle", null)
                        .WithMany()
                        .HasForeignKey("NewsArticleId")
                        .IsRequired()
                        .HasConstraintName("FK_NewsTag_NewsArticle");

                    b.HasOne("FUNewsManagementSystemRepository.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .IsRequired()
                        .HasConstraintName("FK_NewsTag_Tag");
                });

            modelBuilder.Entity("FUNewsManagementSystemRepository.Models.Category", b =>
                {
                    b.Navigation("InverseParentCategory");

                    b.Navigation("NewsArticles");
                });

            modelBuilder.Entity("FUNewsManagementSystemRepository.Models.NewsArticle", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("FUNewsManagementSystemRepository.Models.SystemAccount", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("NewsArticles");
                });
#pragma warning restore 612, 618
        }
    }
}
